downgrade python to 2.1.0 from 2.4.0
This sucks, but that version is causing various date issues.
This is the same version as tamland[0].

21:46:58.042 T:139931911423744   ERROR: GetDirectory - Error getting
21:47:35.521 T:139931099850496   ERROR: Previous line repeats 9 times.
21:47:35.521 T:139931099850496   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.AttributeError'>
                                            Error Contents: 'NoneType' object has no attribute 'day'
                                            Traceback (most recent call last):
                                              File "/home/scanf/.kodi/addons/plugin.video.frikanalen/main.py", line 4, in <module>
                                                addon.run()
                                              File "/home/scanf/.kodi/addons/plugin.video.frikanalen/addon.py", line 77, in run
                                                plugin.run()
                                              File "/home/scanf/.kodi/addons/script.module.routing/lib/routing.py", line 109, in run
                                                self._dispatch(path)
                                              File "/home/scanf/.kodi/addons/script.module.routing/lib/routing.py", line 120, in _dispatch
                                                view_func(**kwargs)
                                              File "/home/scanf/.kodi/addons/plugin.video.frikanalen/addon.py", line 61, in schedule
                                                today_program = frikanalen.today_programs()
                                              File "/home/scanf/.kodi/addons/plugin.video.frikanalen/frikanalen.py", line 74, in today_programs
                                                return [item for item in items if is_today(item.starttime) == True]
                                              File "/home/scanf/.kodi/addons/plugin.video.frikanalen/frikanalen.py", line 69, in is_today
                                                return t.day == datetime.datetime.today().day
                                            AttributeError: 'NoneType' object has no attribute 'day'
                                            -->End of Python script error report<--
21:47:35.528 T:139933709437376   ERROR: GetDirectory - Error getting plugin://plugin.video.frikanalen/schedule

[0]: https://github.com/tamland/xbmc-addon-nrk/blob/master/addon.xml#L7