use new signature for `xbmcplugin.addDirectoryItem`
The `streamurl` parameter is renamed to `url`. This resolves
an exception I was experiencing:

12:30:55 849.251953 T:1592783936  NOTICE: -->Python Interpreter Initialized<--
12:30:55 849.303955 T:1592783936   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.TypeError'>
                                            Error Contents: Required argument 'url' (pos 2) not found
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.frikanalen/default.py", line 29, in <module>
                                                xbmcplugin.addDirectoryItem(handle=addon_handle, streamurl=streamurl, listitem=li)
                                            TypeError: Required argument 'url' (pos 2) not found
                                            -->End of Python script error report<--
12:30:55 849.534668 T:1966813184   ERROR: GetDirectory - Error getting plugin://plugin.video.frikanalen/
12:30:55 849.539124 T:1966813184   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.frikanalen/) failed